FROM node:18-alpine

WORKDIR /usr/src/app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./
COPY apps/frontend/package.json apps/frontend/
COPY apps/frontend ./apps/frontend
COPY packages ./packages

RUN pnpm install --no-frozen-lockfile
RUN pnpm turbo run build --filter=frontend

WORKDIR /usr/src/app/apps/frontend

ENV NODE_ENV=production
EXPOSE 3000

CMD ["pnpm", "start"]
