FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./
COPY apps/http-backend ./apps/http-backend
COPY packages ./packages

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install --no-frozen-lockfile

RUN pnpm db:generate

RUN pnpm --filter http-backend build

WORKDIR /usr/src/app/apps/http-backend

EXPOSE 3001

CMD ["pnpm" , "start"]