

FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml turbo.json pnpm-workspace.yaml ./

COPY apps/ws-backend ./apps/ws-backend
COPY packages ./packages

RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install --frozen-lockfile --filter=ws-backend...

RUN pnpm db:generate || echo "Skipping db:generate"

RUN pnpm --filter ws-backend build

WORKDIR /usr/src/app/apps/ws-backend

EXPOSE 8080

CMD ["pnpm", "start"]
